spring:
  application:
    name: useregistrationsystem
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/registrations?createDatabaseIfNotExist=true
    username: root
    password: root@12
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update