spring:
  application:
    name: useregistrationsystem
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/registrations?createDatabaseIfNotExist=true
#    url: jdbc:mysql://192.875.875.354:3306/registrations?createDatabaseIfNotExist=true   (not working need to find out the solution for this issue)
#    url: jdbc:mysql://localhost:3306/registrations?createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root@12}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update